[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "allin1"
version = "0.0.1"
dependencies = [
  "numpy",
  "madmom",
  "librosa",
  "natten",
  "demucs",
  "hydra-core",
  "omegaconf",
  "huggingface_hub",
]

[project.scripts]
allinone = "allinone.cli:main"
