[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "simpex"
version = "1.0.0"
description = "simpex is a Python library that simplifies the process of using regular expressions (regex)."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.7"
authors = [
  {name = "s41r4j"}
]
maintainers = [
  {name = "s41r4j"}
]
keywords=['python', 'regex', 'simpex', 'regular-expressions', 's41r4j']
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable"
]
dependencies = ['requests']


[project.urls]
"Homepage" = "https://github.com/s41r4j/simpex"
"Wiki" = "https://github.com/s41r4j/simpex/wiki"
"Bug Tracker" = "https://github.com/s41r4j/simpex/issues"