[tool.poetry]
name = "doelab"
version = "0.1.1.dev"
description = "A python package for Design of Experiment(DOE)"
authors = ["caron14 <**.**@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "doelab", from = "./" }]
include = [{ path = "tests", format = "sdist" }]
repository = "https://github.com/**"
keywords = ["DOE", "doelab"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "<3.13,>=3.9"

pandas = ">=1.5.3"
numpy = "<1.24,>=1.18"
scipy = ">=1.11.1"
matplotlib = ">=3.7.2"
seaborn = ">=0.12.2"
plotly = "^5.16.0"
scikit-learn = ">=1.3.0"
tqdm = "^4.66.1"
jupyterlab = "^4.0.5"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[tool.poetry.group.typing.dependencies]
mypy = ">=1.0"
black = {extras = ["jupyter"], version = "^23.7.0"}
flake8 = "^6.1.0"
isort = {extras = ["colors"], version = "^5.12.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
