[project]
name = "pytest-nose-attrib"
version = "0.1.1"
readme = "README.md"
description = "pytest plugin to use nose @attrib marks decorators and pick tests based on attributes and partially uses nose-attrib plugin approach"
authors = [
  { name = "Maksim Gelbakhiani", email = "Max.Gelbakhiani@gmail.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    'pytest >=2.2'
    ]

[project.urls]
Homepage = "https://github.com/MaxGelbakhiani/pytest-nose-attrib"

[project.entry-points."pytest11"]
attr = "pytest_nose_attrib.plugin"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
