info:
  description: This cube is the new api which will be integrated in CubicWeb 4.
  license:
    name: LGPL
    url: https://www.gnu.org/licenses/lgpl-3.0.en.html
  contact:
    name: LOGILAB S.A. (Paris, FRANCE)
    url: https://forge.extranet.logilab.fr/cubicweb/cubes/api
    email: contact@logilab.fr
  title: CubicWeb API
  version: 0.1.0
paths:
  /schema:
    x-pyramid-route-name: schema
    get:
      description: Returns this instance's Schema
      responses:
        '200':
          description: This instance's Schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CWSchema'
  /rql:
    x-pyramid-route-name: rql
    post:
      description: Executes the given RQL query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RqlParams'
      responses:
        '200':
          description: The RQL result set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultSet'
        '400':
          description: The given RQL was badly formatted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSchema'
  /transaction:
    x-pyramid-route-name: transaction
    post:
      description: Execute several queries in a single transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RqlTransactionParams'
      responses:
        '200':
          description: This instance's Schema
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResultSet'
  /login:
    x-pyramid-route-name: login
    post:
      description: Tries to log in the user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginParams'
      responses:
        '204':
          description: Token has been created and returned in set-cookie header
          headers:
            Set-Cookie:
              description: The created JWT
              schema:
                type: string
        '401':
          description: THe given login/password combo was not recognized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorSchema'
  /current-user:
    x-pyramid-route-name: current_user
    get:
      description: Get information about the user making the request
      responses:
        '200':
          description: This instance's Schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUser'
openapi: 3.0.3
components:
  schemas:
    CWSchema:
      type: object
      properties:
        entities:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              description:
                type: string
              final:
                type: boolean
        relations_definitions:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              description:
                type: string
              final:
                type: boolean
              subject:
                type: string
              object:
                type: string
              cardinality:
                type: string
              constraints:
                type: array
                nullable: true
              default:
                type: string
                nullable: true
    RqlParams:
      type: object
      properties:
        query:
          type: string
          minLength: 1
        params:
          type: object
          default: {}
          additionalProperties:
            $ref: '#/components/schemas/RqlParamsValue'
      required:
        - query
    RqlParamsValue:
      oneOf:
        - type: string
          nullable: true
        - type: number
        - type: boolean
    RqlTransactionParams:
      type: object
      properties:
        query:
          type: string
          minLength: 1
        params:
          type: object
          default: {}
          additionalProperties:
            $ref: '#/components/schemas/RqlTransactionParamsValue'
      required:
        - query
    RqlTransactionParamsValue:
      oneOf:
        - type: string
          nullable: true
        - type: number
        - type: boolean
        - type: object
          properties:
            queryIndex:
              type: number
            row:
              type: number
            column:
              type: number
          additionalProperties: false
    LoginParams:
      type: object
      properties:
        password:
          type: string
          minLength: 1
        login:
          type: string
          minLength: 1
      required:
        - login
        - password
    ErrorSchema:
      type: object
      properties:
        code:
          type: integer
        title:
          type: string
        error:
          type: object
          properties:
            data:
              type: object
            message:
              type: string
            title:
              type: string
          required:
            - message
            - title
      required:
        - code
        - title
        - error
    ResultSet:
      type: array
      items:
        type: array
        items:
          oneOf:
            - type: 'string'
              nullable: true
            - type: 'number'
            - type: 'boolean'
    CurrentUser:
      type: object
      nullable: true
      properties:
        eid:
          type: integer
        login:
          type: string
        dcTitle:
          type: string
      required:
        - eid
        - login
        - dcTitle
