[build-system]
requires = ["hatchling>=1.5"]
build-backend = "hatchling.build"

[project]
name = "jupyter_sentry_extension"
authors = [{name = "Pavel Komar", email = "pvkomar@cloud.ru"}]
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.8"
keywords = ["Jupyter", "Extension"]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Framework :: Jupyter",
]
dependencies = ["jupyter_server>=1.6,<3", "sentry-sdk>=1.5.5"]

[project.optional-dependencies]
lint = [
  "black>=22.6.0",
]

[project.license]
file="LICENSE"

[tool.hatch.version]
path = "jupyter_sentry_extension/__init__.py"

[tool.hatch.build.targets.wheel.shared-data]
"jupyter-config" = "etc/jupyter"

[tool.autoflake]
# make changes to files instead of printing diffs
in-place = true
# drill down directories recursively
recursive = true
# remove all unused imports (not just those from the standard library)
remove-all-unused-imports = true
# exclude __init__.py when removing unused imports
ignore-init-module-imports = true
# remove unused variables
remove-unused-variables = true

[tool.isort]
# multiline output option: there are 10 options
multi_line_output = 3
# max line-length whithin the project
line_length = 140
# includes a trailing comma on multi line imports that include parentheses.
include_trailing_comma= true
# number of lines after imports section
lines_after_imports = 2

[tool.black]
# max line-length whithin the project
line-length = 140
# version of Python within the project
target-version = ["py38"]
