[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "JWDeviceDB"
version = "0.0.1"
authors = [
  { name="JW", email="JW@dev.null" },
]
description = "Device DB"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://dev.null"
"Bug Tracker" = "https://dev.null"
