name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Clone w/ submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Python Formatting
        uses: psf/black@stable
        with:
          options: --check --extend-exclude '/(ext|doc/scripts/.*_theme|doc/scripts/inputs.py)'
          src: .
      - name: Python analysis
        run: |
          flake8 .
