[tool.poetry]
name = "outline-sdk"
version = "0.1.0"
description = "Async Python SDK wrapper for Outline Manager VPN"
authors = ["Denis Malin <denis@malina.page>"]
license = "MIT License"
readme = "README.md"
packages = [
    { include = "outline_sdk" }
]

[tool.poetry.dependencies]
python = "^3.11"
uvloop = "^0.17.0"
pyrogram = "^2.0.106"
aio-clients = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
