[tool.poetry]
name = "plasmodia"
version = "0.0.0"
description = "The complete framework for interactive learning."
authors = ["RenChu Wang <patrick1031wang@gmail.com>"]
license = "Apache"
readme = "README.md"

[tool.poetry.dependencies]
aim = "^3.17.5"
alive-progress = "^3.1.4"
dm-reverb = "^0.11.0"
gymnasium = "^0.28.1"
omegaconf = "^2.3.0"
python = ">=3.10,<3.11"
tensordict = "^0.1.2"
torch = "^2.0.0"
pettingzoo = "^1.23.1"
rich = "^13.4.2"
ray = "^2.5.0"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.1.1"
black = "^23.3.0"
ipython = "^8.14.0"
isort = "^5.12.0"
pytest = "^7.3.1"
pytype = "^2023.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
