[build-system]
requires = ["setuptools", "wheel", "flit_core"]
build-backend = "flit_core.buildapi" # flit_core.buildapi | setuptools.build_meta

[tool.flit.metadata]
module = "microservice_shared"
description-file = "README.md"
author = "Manikandan"
author-email = "manikandan.findmyjobz@gmail.com"
home-page = "https://findmyjobz.com"
license = "MIT"
keywords = "job search"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11"
]

[tool.flit.scripts]
# Add any entry points or scripts here if needed

[tool.poetry]
name = "microservice_shared"
version = "0.3.0"
description = "Microservice Shared Package"
authors = ["Manikandan <manikandan.findmyjobz@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
django = "^4.1"
djangorestframework = "^3.14.0"
python = "3.11.4"
build = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
twine = "4.0.2"