[tool.poetry]
name = "intel-toolkit"
version = "0.1.1"
description = "Toolkit with methods to consume vulnerability risk mapping APIs"
authors = ["cristianovisk <cristianovisk@gmail.com>"]
readme = "README.md"
packages = [{include = "intel_toolkit"}]

[tool.poetry.dependencies]
python = "^3.10"
httpx = {extras = ["http2"], version = "^0.24.1"}
rich = "^13.5.2"
requests = "^2.31.0"
colorama = "^0.4.6"
prettytable = "^3.8.0"
pyfiglet = "^0.8.post1"
pyshorteners = "^1.0.1"
orjson = "^3.9.4"
brotli = "^1.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
