[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "unbounded-data"
version = "0.41.1"
authors = ["Unbounded Network"]
description = "The Unbounded Network Data Python interface"

[tool.poetry.dependencies]
  "python" = "^3.10"
  "pandas" =  "^1.4.3"
  "gql" = "^3.4.0"
  "python-benedict" = "^0.25.2"
  "aiohttp" = "^3.8.3"
  "openpyxl" = {version="^3.0.10", optional=true}
  "pyarrow" = {version="^9.0.0", optional=true}
  
[tool.poetry.dev-dependencies]
  "pytest" = "^7.1.2"
  "pytest-mock" = "^3.8.2"
  "pytest-aiohttp" = "^1.0.4"
  "pytest-asyncio" = "^0.19.0"
  "python-semantic-release" = "^7.31.2"
  "pylint" = "^2.14.5"
  "openpyxl" = "^3.0.10"
  "pyarrow" = "^9.0.0"

[tool.semantic_release]
  version_toml = [
      "pyproject.toml:tool.poetry.version"
  ]
  branch = "main"
  hvcs = "gitlab"
  commit_message = "[skip ci] version bump"
  build_command = "poetry build"
