[tool.poetry]
name = "sci-mls"
version = "0.0.0"
license = "BSD-3-Clause"
description = "The friendly scientific machine learning library"
authors = ["altar31 <damien.sicard31@gmail.com>"]
readme = "README.md"
packages = [{include = "sciml"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.3"
keras = "^2.13.1"
scikit-learn = "^1.3.0"
seaborn = "^0.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
