[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MovingBot"
version = "0.0.1"
authors = [
  { name="XKMR", email="author@example.com" },
]
description = "a script for simulating a object with a direction that can move in said direction"
readme = "README.md"
requires-python = ">3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/XKMR/PythonMovingBot"
"Bug Tracker" = "https://github.com/XKMR/PythonMovingBot/issues"