[tool.poetry]
name = "doelab"
version = "0.1.1"
description = "A python package for Design of Experiment(DOE)"
authors = ["caron14 <**.**@gmail.com>"]
readme = "README.md"
packages = [
    { include = "common", from = "doelab" },
    { include = "doe", from = "doelab" },
    { include = "analysis", from = "doelab" },
]

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
black = {extras = ["jupyter"], version = "^23.7.0"}
flake8 = "^6.1.0"
isort = {extras = ["colors"], version = "^5.12.0"}
mypy = "^1.5.0"
pytest = "^7.4.0"
pandas = ">=1.5.3"
numpy = "<1.24,>=1.18"
scipy = ">=1.11.1"
matplotlib = ">=3.7.2"
seaborn = ">=0.12.2"
plotly = "^5.16.0"
scikit-learn = ">=1.3.0"
tqdm = "^4.66.1"
jupyterlab = "^4.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
