[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "test-saurabh0402"
version = "0.0.6"
authors = [
  "Saurabh <saurabh.kumar@peak.ai>",
]
description = "A small example package"
readme = "docs.md"
homepage = "https://github.com/saurabh0402/padhai"
documentation = "https://github.com/saurabh0402/padhai"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
