[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tablate"
version = "0.1.10"
authors = [
  { name="Guy de Winton", email="guy@codehippie.io" },
]
description = "A highly customizable ASCII and HTML table renderer for IPython & CLI applications."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.urls]
"Homepage" = "https://gitlab.com/guydewinton/tablate"
"Documentation" = "https://tablate.readthedocs.io/en/latest/"


[tool.setuptools.packages.find]
exclude = ["docs", "tests"]



