[tool.poetry]
name = "magicml"
version = "0.0.0"
description = "The machine learning model interface"
authors = ["altar31 <damien.sicard31@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
dash = "^2.11.1"
pandas = "^2.0.3"
keras = "^2.13.1"
scikit-learn = "^1.3.0"
mlflow = "^2.5.0"
seaborn = "^0.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"