[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "simple-notifications"
description = "Send notfications by email or webhook"
authors = [
    {name = "Christoph Stein" }
]
requires-python = ">=3.9"
version = "0.1.2"
#dependencies = [
#    "requests",
#    "urllib3",
#]
keywords = ["Email", "Notifications"]
readme = "README.md"
#license = {file = "LICENSE.txt"}
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Environment :: Console"
]

[project.urls]
homepage = "https://gitlab.com/s7one/simple-notifications"
documentation = "https://gitlab.com/s7one/simple-notifications"
repository = "https://gitlab.com/s7one/simple-notifications"
