[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hzexcel"
version = "0.0.1"
authors = [
  { name="myliao Nathen", email="1739951529@qq.com" },
]
description = "提供常用django、Python后端的excel导入导出功能"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"