[tool.poetry]
name = "poetry-packaging"
version = "0.3.0"
description = ""
authors = ["Burhan523 <burhanuddin@mentorskool.com>"]
readme = "README.md"
packages = [{include = "poetry_packaging"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
pandas = "^2.0.3"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
