[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mathex"
version = "0.1.0"
authors = [{ name = "Caps Lock", email = "lockedcapsey@gmail.com" }]
description = "Package for Python that evaluates math expressions from strings"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/capsey/mathex-py"
"Bug Tracker" = "https://github.com/capsey/mathex-py/issues"
