[tool.poetry]
name = "poem-fa"
version = "0.2.0"
description = ""
authors = ["Mehdi Ghodsizadeh <m.ghodsizadeh@gmail.com>"]
readme = "README.md"
packages = [{include = "poem_fa"}]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.9.0"
python-bidi = "^0.4.2"
arabic-reshaper = "^3.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
