[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "PyMalware"
authors = [
    {name = "PthePro777 YT", email = "pthepro777ytb@gmail.com"},
]
description = "A python package to make malware creation easier"
readme = "README"
requires-python = ">=3.7"
keywords = ['Malware', 'Advanced', 'Python', 'Dev']
classifiers=[
    'Development Status :: 3 - Alpha',      # Chose either "3 - Alpha", "4 - Beta" or "5 - Production/Stable" as the current state of your package
    'Intended Audience :: Developers',      # Define that your audience are developers
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',   # Again, pick a license
    'Programming Language :: Python :: 3',      #Specify which pyhton versions that you want to support
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.11',
]
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
]
version = "1.0"

  