[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "curt"
version = "0.0.2"
authors = [
  { name="Jahaziel Alvarez", email="jahaziel.alvarez@proton.me" },
]
description = "CuRT allows to generate a specific number of RPS to a webservice. Permite generar un número específico de peticiones por segundo a un servicio web."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/jahaziel-alvarez/curt"
"Bug Tracker" = "https://gitlab.com/jahaziel-alvarez/curt/issues"