[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydepsdev"
version = "0.1.2"
authors = [
  { name = "Robert-André Mauchin", email = "zebob.m@gmail.com" }
]
description = "A Python library for interacting with Deps.dev API"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
keywords = ["api", "deps.dev"]
classifiers = [
    "Topic :: Software Development :: Libraries",
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers"
]
dependencies = [
  "aiohttp"
]

[project.urls]
"Homepage"= "https://github.com/eclipseo/pydepsdev"
"Repository" = "https://github.com/eclipseo/pydepsdev.git"
"Bug Tracker" = "https://github.com/eclipseo/pydepsdev/issues"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38, py39, py310, py311, lint

[testenv]
deps = pytest >= 3.0.0, aioresponses, pytest-asyncio
commands = pytest

[testenv:lint]
deps = black
commands = black pydepsdev
"""
