[tool.poetry]
name = "cheapcone"
version = "0.1.10"
description = ""
authors = ["Oscar Bahamonde <oscar.bahamonde@pucp.pe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.8.5"
python-dotenv = "^1.0.0"
pydantic = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
