[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snake_gpm"
version = "0.0.1"

[project.scripts]
snakey = "snake.__main__:main"