name: Run tests

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
    
    - name: Install local package
      run: python -m pip install .
    
    - name: Run tests
      run: pytest
