[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"


[project]
name = "glinski"
version = "0.1.0"
description = "glinski"
license = { file = "LICENSE" }
authors = [{ name = "Aaron Alphabet", email = "aaron.alphabet@posteo.org" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = []
dependencies = [
    "isometric>=1.0.0",
]
requires-python = ">=3.11"

