[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "dvsgc"
version = "0.1.2"
authors = [
  { name="VicenteAlex", email="alex.vicente-sola@strath.ac.uk" },
]
description = "DVS-Gestures-Chain. Implementation of the dataset defined in \"Spiking Neural Networks for event-based action recognition: A new task to understand their advantage\""
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "spikingjelly==0.0.0.0.8",
    "torchvision",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/VicenteAlex/DVS-Gesture-Chain"
"Bug Tracker" = "https://github.com/VicenteAlex/DVS-Gesture-Chain/issues"