[build-system]
requires = ["setuptools>=61.0", "keras"]
build-backend = "setuptools.build_meta"

[project]
name = "O2RM-Model"
version = "0.0.1"
authors = [
  { name="Kent vejrup Madsen", email="kent.vejrup.madsen@designermadsen.dk" },
]
description = "Model to recognise symbols & letters"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/KentVejrupMadsen/O2RM-Model"
"Bug Tracker" = "https://github.com/KentVejrupMadsen/O2RM-Model/issues"