[tool.poetry]
name = "memsparkline"
version = "0.3.2"
description = "Track the RAM usage (resident set size) of a process and its descendants in real time."
authors = ["D. Bohdan <dbohdan@dbohdan.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/dbohdan/memsparkline"
keywords = ["memory", "monitoring", "performance", "RAM", "resident set size", "sparklines"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Topic :: System :: Benchmark",
    "Topic :: System :: Monitoring",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.7"
psutil = "^5.9.5"

[tool.poetry.group.dev.dependencies]
types-psutil = "^5.9.5.15"
black = "^23.3.0"
ruff = "^0.0.277"
pytest = "^7.4.0"
pyright = "^1.1.318"

[build-system]
requires = ["poetry-core>=1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
memsparkline = 'memsparkline:main'
