[tool.poetry]
name = "fake-chat"
version = "0.1.0"
description = ""
authors = ["Aurorax-own <15047150695@163.com>"]
readme = "README.md"
packages = [{ include = "fake_chat" }]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.26.0"
Pandora-ChatGPT = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
