[tool.poetry]
name = "codelimit"
version = "0.2.1"
description = ""
authors = ["Rob van der Leek <robvanderleek@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
codelimit = "codelimit.__main__:cli"
hook = "codelimit.__main__:pre_commit_hook"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
halo = "^0.0.31"
plotext = "^5.2.8"
pygments = "^2.13.0"
textual = {extras = ["dev"], version = "^0.10.1"}
requests = "^2.28.2"
typer = "^0.9.0"

[tool.poe.tasks.bundle]
help = "Create a binary executable using pyinstaller"
cmd = "pyinstaller --workpath .build --specpath dist -n codelimit -F codelimit/__main__.py"

[tool.semantic_release]
version_toml = [ "pyproject.toml:tool.poetry.version" ]
version_variables = [ "codelimit/version.py:version" ]
branch = "main"
upload_to_repository = false
upload_to_release = false
commit_parser = "emoji"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.6.1"
pytest-cov = "^4.0.0"
pytest = "^7.2.1"
poethepoet = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
