[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "securitycopilot"
version = "0.0.1"
authors = [
  { name="Mark Kendrick", email="aeetos@gmail.com" },
]
description = "securitycopilot"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/aeetos/securitycopilot"
"Bug Tracker" = "https://github.com/aeetos/securitycopilot/issues"