[build-system]
requires = ["setuptools>=42", "wheel", "cython>=0.27.3", "numpy>=1.16.2"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "rays_pycocotools"
version = "2.6.6"
description = "Wrapper of pycocotools that correctly installs with pip."
readme = "README.md"
requires-python = ">=3.6"
dependencies = ["setuptools>=18.0", "cython>=0.27.3", "numpy>=1.16.2"]

[project.optional-dependencies]
all = ["matplotlib>=2.1.0"]
