[tool.poetry]
name = "lux-discord"
version = "0.1.0"
description = "Lightweight Python Discord bot framework"
authors = ["Euxcbsks <hawhaw02030746@gmail.com>"]
license = "MIT license"
readme = "README.md"
packages = [{ include = "lux", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.6"
disnake = "^2.9.0"
pydantic = "^2.1.1"

beanie = { version = "^1.20.0", optional = true }
colorlog = { version = "^6.7.0", optional = true }
python-dotenv = { version = "^1.0.0", optional = true }

[tool.poetry.extras]
dotenv = ["python-dotenv"]
colorlog = ["colorlog"]
mongodb = ["beanie"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
target-version = "py311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
