[tool.poetry]
name = "noah-cli"
version = "0.1.0"
description = ""
authors = ["raymond-u <36328498+raymond-u@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "noah-cli", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.9.0"}
fabric = "^3.1.0"
pysradb = "^2.1.0"
requests = "^2.31.0"
dacite = "^1.8.1"
ordered-set = "^4.1.0"
ruamel-yaml = "^0.17.32"

[tool.poetry.scripts]
noah = "noah-cli.app.main:app"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
