[tool.poetry]
name = "yann-utils"
version = "0.1.1"
description = ""
authors = ["Yann Hoffmann <yann.hoffmaaann@gmail.com>"]
readme = "README.md"
packages = [{include = "yann_utils"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.25.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
