[tool.poetry]
name = "deciphon-core"
version = "0.14.4"
description = "Python wrapper around the Deciphon C library"
authors = ["Danilo Horta <horta@ebi.ac.uk>"]
license = "MIT"
readme = "README.md"
include = [
  { path = "deciphon_core/*.so", format = "wheel" },
  { path = "deciphon_core/*.pyd", format = "wheel" },
  { path = "deciphon_core/lib/lib*", format = "wheel" },
  { path = "build_ext.py", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.9"
cffi = "^1.15.1"
pydantic = "^2"

[tool.poetry.build]
script = "build_ext.py"
generate-setup-file = false

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
h3daemon = "^0"

[build-system]
requires = ["poetry-core", "cffi", "cmake", "patchelf;sys_platform=='linux'"]
build-backend = "poetry.core.masonry.api"

[tool.cibuildwheel]
skip = ["*i686"]
