[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "parsanlp"
version = "1.0.2"
authors = [
  { name="Parsa Hemmati" },
]
description = "A package to help with NLP tasks"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]