[tool.poetry]
name = "deciphon"
version = "0.9.2"
description = "Individually annotate long, error-prone nucleotide sequences into proteins"
authors = ["Danilo Horta <horta@ebi.ac.uk>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "deciphon" }]

[tool.poetry.dependencies]
python = "^3.9"
cffi = "^1.15.1"
deciphon-core = "^0.13.2"
deciphon-snap = "^0.5.2"
fasta-reader = "^3.0.2"
h3daemon = "^0.13.5"
hmmer = "^0.2.4"
ijson = "^3.2.3"
pydantic = "^2.1.1"
typer = "^0.9.0"
rich = "^13.5.2"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
deci = 'deciphon.cli:app'
