[build-system]
requires = ["hatchling>=1.5"]
build-backend = "hatchling.build"

[project]
name = "ipython_sentry_extension"
authors = [{name = "Pavel Komar", email = "pvkomar@cloud.ru"}]
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["Jupyter", "Extension"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = ["ipython>=7.0.0", "sentry-sdk>=1.5.5"]


[tool.autoflake]
# make changes to files instead of printing diffs
in-place = true
# drill down directories recursively
recursive = true
# remove all unused imports (not just those from the standard library)
remove-all-unused-imports = true
# exclude __init__.py when removing unused imports
ignore-init-module-imports = true
# remove unused variables
remove-unused-variables = true

[tool.isort]
# multiline output option: there are 10 options
multi_line_output = 3
# max line-length whithin the project
line_length = 140
# includes a trailing comma on multi line imports that include parentheses.
include_trailing_comma= true
# number of lines after imports section
lines_after_imports = 2

[tool.black]
# max line-length whithin the project
line-length = 140
# version of Python within the project
target-version = ["py38"]
