[tool.poetry]
name = "easyebay"
version = "0.1.1"
description = "A library for scraping items from eBay"
authors = ["DrEgg <public@dregg.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.12.2"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
