[tool.poetry]
name = "scaffolding_python"
version = "0.1.0"
description = ""
authors = ["eduardo.zapata <eduardo.zapata@wayops.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.6"
opencensus-ext-azure = "^1.1.9"
fastapi = "^0.101.0"
uvicorn = "^0.23.2"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pdbp = "^1.4.3"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
my-script = "scaffolding_python.script_for_toml:start"
coins = "scaffolding_python.combinations_coins.__main__:start"
fibonacci = "scaffolding_python.fibonacci_exercise.__main__:start"
