[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ohmydata"
version = "0.2"
authors = [
  { name="Crillerium", email="crillerium@outlook.com" },
]
description = "An Easy Database Basd On Json"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Home-page" = "https://github.com/crillerium/"
