[build-system]
requires = ["setuptools>=61.2",
            "setuptools_scm[toml]>=3.4.3",
            "wheel"]
build-backend = 'setuptools.build_meta'

[project]
name = "grig"
description = "N-Dimensional Resampler for Irregularly Gridded Data"
authors = [{name = "SOFIA-USRA", email = "mclarke@sofia.usra.edu"}]
license = {file = "LICENSE.rst"}
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "bottleneck>=1.3.7",
    "cloudpickle>=2.2.1",
    "joblib>=1.3.0",
    "numba>=0.57.1",
    "numpy>=1.24.4",
    "psutil>=5.9.5",
    "scikit-learn>=1.3.0",
    "scipy>=1.11.1"
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics"
]
readme = "README.rst"

[project.optional-dependencies]
test = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "ruff",
]
docs = [
    "graphviz",
    "imageio",
    "matplotlib>=3.7.2",
    "numpydoc>=1.5.0",
    "sphinx>=5",
    "sphinx_rtd_theme",
    "sphinx-automodapi",
    "sphinx-issues",
    "tomli"
]

[project.urls]
Homepage = "https://github.com/SOFIA-USRA/grig"

[tool.setuptools.package-data]
grig = ["data/*"]

[tool.setuptools_scm]
write_to = "grig/version.py"

[tool.pytest.ini_options]
minversion = "2.2"
testpaths = ["grig",]
norecursedirs = [
    "build",
    "docs/_build",
]
doctest_plus = "enabled"
text_file_format = "rst"
addopts = "-p no:warnings"


[tool.coverage.run]
source = ["grig",]
omit = [
    "grig/tests/*",
    "grig/*/tests/*",
    "grig/version*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "except ImportError",
    "raise AssertionError",
    "raise NotImplementedError",
    "def main(.*):",
    "pragma: py{ignore_python_version}",
]
omit = [
    "grig/tests/*",
    "grig/*/tests/*",
    "grig/version*",
]

[tool.ruff]
exclude = [
    "version.py",
    "conf.py"
]
ignore = []
line-length = 79
select = ["E", "F", "W"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F403"]

[tool.ruff.pydocstyle]
convention = "numpy"
