[project]
name = "gwp_uncertainties"
version = "0.3.dev1"
authors = [
  { name="Aleksandra Kim", email="aleksandra.kim@icloud.com" },
]
description = "This package computes uncertainties in GWP values for a number of substances as described in the IPCC 2013 report."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/aleksandra-kim/gwp_uncertainties"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["gwp_uncertainties"]
