[build-system]
requires = ["setuptools", "wheel", "flit_core"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "microservice_shared"
author = "Manikandan"
author-email = "manikandan.findmyjobz@gmail.com"
home-page = "https://findmyjobz.com"
requires-python = "3.11"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11"
]

[tool.flit.scripts]
# Add any entry points or scripts here if needed

[tool.flit.metadata.requires]
# The requires field should be a list

[tool.flit.metadata.optional.requires]
# Add optional dependencies here, if any

[tool.poetry]
name = "microservice_shared"
version = "0.2.0"
description = "Microservice Shared Package"
authors = ["Manikandan <manikandan.findmyjobz@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
django = "^4.1"
djangorestframework = "^3.14.0"
python = "^3.11"
build = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
twine = "4.0.2"