[project]
name = "kylink"
version = "0.0.1"
authors = [
  { name="KyLink", email="kylink@protonmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/njublockchain/pylinkit"
"Bug Tracker" = "https://github.com/njublockchain/pylinkit/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
