[build-system]
requires = [
    "hatchling"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_store"
version = "0.2.0"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, pennyeach (object storage modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "minio>=7.1.15",
    "pip>=23.2.1",
    "pypomes_core>=0.2.6",
    "setuptools>=68.0.0",
    "Unidecode>=1.3.6",
    "wheel>=0.41.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Store"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Store/issues"
