[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "roleft"
version = "1.0.8"
authors = [{ name = "wenzd", email = "october731@163.com" }]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# dependencies = ["PyExecJS", "requests", "pandas"]
[project.urls]
"Homepage" = "https://roleft.com"
