[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lemmy_mod_bot"
version = "0.0.5"
authors = [
  { name="noenfugler", email="noenfugler@greenwolf.com.au" },
]
description = "lemmy_mod_bot is a Lemmy Mod Bot written in Python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/noenfugler/LemmyModBot"
"Bug Tracker" = "https://github.com/noenfugler/LemmyModBot/issues"