[tool.poetry]
name = "fastgoertzel"
version = "0.1.1"
description = "Cython Goertzel algorithm implemented in 3 ways"
authors = ["Nicholas Picini <ozeanwave@gmail.com>"]
readme = "README.md"
license = "MIT"
exclude = ["src/**/*.py"]
include = [
    "src/**/*.so",
    "LICENSE"
] 

[tool.poetry.dependencies]
python = "<3.13 >=3.9"
numpy = "=1.25.2"
scipy = "=1.11.1"

[tool.poetry.dev-dependencies]
cython = "=3.0.0"

[build-system]
requires = ["poetry-core", "cython"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"
