[tool.poetry]
name = "pdf_scrapper"
version = "0.1.0"
description = "Pdf Scrapping interface"
authors = ["Otmane Alami <79752114+otmanealami@users.noreply.github.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
pdfplumber = "^0.9.0"
streamlit = "^1.24.1"
pytesseract = "^0.3.10"
pdf2image = "^1.16.3"
pypdf2 = "^3.0.1"
tqdm = "^4.65.0"
pip = "^23.1.2"
install = "^1.3.5"
openpyxl = "^3.1.2"
lxml = "^4.9.3"
pyoxidizer = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
