# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://juejin.cn/post/6982168137609248805
default_language_version:
    python: python3.11.1
repos:
-   repo: https://gitee.com/lijc210/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# -   repo: https://gitee.com/lijc210/ruff-pre-commit
#     rev: v0.0.254
#     hooks:
#     -   id: ruff
#         args:
#         - --fix
# -   repo: https://gitee.com/lijc210/isort
#     rev: 5.12.0
#     hooks:
#     -   id: isort
#         name: isort (python)
#     -   id: isort
#         name: isort (cython)
#         types: [cython]
#     -   id: isort
#         name: isort (pyi)
#         types: [pyi]
# -   repo: https://gitee.com/lijc210/black
#     rev: 23.1.0
#     hooks:
#     -   id: black
-   repo: local
    hooks:
      - id: black
        name: Run black
        entry: black
        language: system
        types: [python]
      - id: pyupgrade
        name: Run pyupgrade
        entry: pyupgrade
        language: system
        types: [python]
        args:
        - --py3-plus
        - --keep-runtime-typing
ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate