[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dkdc"
version = "0.0.2"
authors = [
  { name="Cody", email="cody@dkdc.dev" },
]
description = "dkdc"
readme = "readme.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/lostmygithubaccount/dkdc"
"Bug Tracker" = "https://github.com/lostmygithubaccount/dkdc/issues"
