[project]
name = "dinja"
version = "0.1.0"
description = "Singleton class that provides decorators to create custom **`filters`** and **`tags`** for Jinja templates"
authors = [
    { name = "hlop3z", email = "23062270+hlop3z@users.noreply.github.com" },
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool]
