[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "overhang_surrogates"
authors = [{name = "Dragan Stevanovic, Marko Milosevic, Sanja Stevanovic", email = "dragan_stevanovic@mi.sanu.ac.rs"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
