[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "roleft"
version = "1.0.5"
authors = [{ name = "wenzd", email = "october731@163.com" }]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["PyExecJS", "requests", "pandas"]
[project.urls]
"Homepage" = "https://roleft.com"
