[tool.poetry]
name = "cmoncrawl_fetcher"
version = "0.1.0"
description = "Fetches files of desired type from common crawler's database"
authors = [
	"Kris Udomwongsa <krisudomwongsa@gmail.com>",
]

license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"

[tool.poetry.urls]
repository = "https://github.com/bread-b4nk/CmonCrawl-Fetcher"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
